# Data Files/MagickaExpanded-WeatherMagicPack-metadata.toml

# Holds basic information about the mod
[package]
name = "Magicka Expanded - Weather Magic Pack"
description = "The Weather Magic Pack module for the Magicka Expanded Framework. Part of the Magicka Expanded BAIN package."
homepage = "https://www.nexusmods.com/morrowind/mods/47111"
repository = "https://github.com/OperatorJack/Magicka-Expanded"
authors = ["OperatorJack", "RedFurryDemon"]
version = "3.0.0"

# MWSE specific information about this mod
[tools.mwse]
lua-mod = "OperatorJack.MagickaExpanded-WeatherMagic"
load-order = 100
wait-until-initialize = true

# Dependencies are checked on `initialized` and warn the player if any are missing
[dependencies]
  # Assets can be directories or loose folders
  assets = [
      "Meshes\\OJ\\ME\\wp\\ashshell_hit.nif",

      "Icons\\RFD\\B_RFD_wth_ash.dds",
      "Icons\\RFD\\B_RFD_wth_blight.dds",
      "Icons\\RFD\\B_RFD_wth_blizz.dds",
      "Icons\\RFD\\B_RFD_wth_clear.dds",
      "Icons\\RFD\\B_RFD_wth_cloud.dds",
      "Icons\\RFD\\B_RFD_wth_fog.dds",
      "Icons\\RFD\\B_RFD_wth_over.dds",
      "Icons\\RFD\\B_RFD_wth_rain.dds",
      "Icons\\RFD\\B_RFD_wth_snow.dds",
      "Icons\\RFD\\B_RFD_wth_storm.dds",
      
      "Icons\\RFD\\RFD_wth_ash.dds",
      "Icons\\RFD\\RFD_wth_blight.dds",
      "Icons\\RFD\\RFD_wth_blizz.dds",
      "Icons\\RFD\\RFD_wth_clear.dds",
      "Icons\\RFD\\RFD_wth_cloud.dds",
      "Icons\\RFD\\RFD_wth_fog.dds",
      "Icons\\RFD\\RFD_wth_over.dds",
      "Icons\\RFD\\RFD_wth_rain.dds",
      "Icons\\RFD\\RFD_wth_snow.dds",
      "Icons\\RFD\\RFD_wth_storm.dds",
  ]

# Check MWSE version using build number (the number that comes after "v2.1.0" in MWSE.log)
[dependencies.mwse]
buildnumber = 3273

# Check MGE XE version
[dependencies.mge-xe]
version = ">=0.15.0"

# mwse-module can be a folder or lua file, anywhere in /mods, /lib etc
[dependencies.mods.MagickaExpanded]
mwse-module = "OperatorJack.MagickaExpanded"
version = ">=3.0.0"